#!/bin/bash
IFS=","


if [[ $1 == 'container' ]]
then
  for path in $4
  do
   echo $path
   rm -rf $path/*
  done

else

  echo /base-backup/$2
  rm -rf /base-backup/$2

fi

directory=/tmp/bup-restore/$2/archive
archive=/tmp/bup-restore/$2/archive.tar.gz

ssh bup-server << EOF
  mkdir -p $directory
  bup restore -C $directory $2/$3
  tar czf $archive -C $directory/$3 .
EOF

mkdir -p $directory
scp -qr bup-server:$archive $archive
tar -xf $archive -C $directory

rm $directory/backup-date

if [[ $1 == 'container' ]]
then

  for path in $directory/*
  do
   echo $path
   cp -R $path /
  done

else

  cp -R $directory /base-backup/$2 
  chmod -R 777 /base-backup/$2

fi

rm -rf /tmp/bup-restore/$2

ssh bup-server << EOF
  rm -rf /tmp/bup-restore/$2
EOF
